pipeline {
    agent any
    
    tools {
        maven 'mymaven'
        jdk 'JDK21'
    }
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/illyees/countryservice.git'
            }
        }
        
        stage('Navigate to project folder') {
            steps {
                sh '''
                    echo "Current directory: $(pwd)"
                    ls -la
                    cd countryservice-main
                    echo "After cd: $(pwd)"
                    ls -la
                '''
            }
        }
        
        stage('Build & Test') {
            steps {
                sh '''
                    cd countryservice-main
                    mvn clean compile
                '''
            }
        }
        
        stage('Unit Tests') {
            steps {
                sh '''
                    cd countryservice-main
                    mvn test
                '''
            }
            post {
                always {
                    junit 'countryservice-main/**/target/surefire-reports/*.xml'
                }
            }
        }
        
        stage('Package') {
            steps {
                sh '''
                    cd countryservice-main
                    mvn package -DskipTests
                '''
            }
        }
        
        stage('Deploy to Tomcat') {
            steps {
                sh 'echo "Deployment to Tomcat would happen here"'
            }
        }
    }
    
    post {
        always {
            echo "Build ${currentBuild.currentResult} - ${env.JOB_NAME} #${env.BUILD_NUMBER}"
        }
    }
}
